spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_boot_ai_fitness_microservices?useSSl=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 3md*ruTuch7D7ub

  jpa:
    generate-ddl: true
    hibernate:
      ddl:
        auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
